version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    restart: on-failure
    depends_on:
      - mailhog
    environment:
      - USE_DOCKER=yes
    volumes:
      - .:/pin
      - ./compose/django/sample:/app
    ports:
      - "${DJANGO_PORT}:8000"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "${MAILHOG_PORT}:8025"

  